---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: 'È possibile distribuire l"operatore Trident e installare Trident utilizzando Helm. Questo processo si applica alle installazioni in cui le immagini contenitore richieste da Trident sono memorizzate in un registro privato.' 
---
= Implementare l'operatore Trident utilizzando Helm (modalità offline)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile distribuire l'operatore Trident e installare Trident utilizzando Helm. Questo processo si applica alle installazioni in cui le immagini contenitore richieste da Trident sono memorizzate in un registro privato. Se non si dispone di un registro delle immagini private, utilizzare link:kubernetes-deploy-helm.html["processo per l'implementazione standard"].



== Informazioni critiche su Trident 25,02

*È necessario leggere le seguenti informazioni critiche su Trident.*

.<strong> informazioni aggiornate su Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1,32 è ora supportato in Trident. Aggiornare Trident prima di aggiornare Kubernetes.
* Trident impone rigorosamente l'uso della configurazione multipath negli ambienti SAN, con un valore consigliato di `find_multipaths: no` nel file multipath.conf.
+
L'utilizzo di una configurazione non multipathing o di `find_multipaths: yes` un valore OR `find_multipaths: smart` nel file multipath.conf determinerà errori di montaggio. Trident ha consigliato l'uso di `find_multipaths: no` fin dalla versione 21,07.



=====
====


== Distribuire l'operatore Trident e installare Trident utilizzando Helm

Utilizzando Trident link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Grafico di comando"^]è possibile distribuire l'operatore Trident e installare Trident in un'unica fase.

Verificare link:../trident-get-started/kubernetes-deploy.html["panoramica dell'installazione"]di aver soddisfatto i prerequisiti di installazione e di aver selezionato l'opzione di installazione corretta per l'ambiente in uso.

.Prima di iniziare
Oltre al link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["prerequisiti per l'implementazione"]necessario link:https://v3.helm.sh/["Helm versione 3"^].


IMPORTANT: Quando si installa Trident in un repository privato, se si utilizza `imageRegistry` lo switch per specificare la posizione del repository, non utilizzare `/netapp/` nel percorso del repository.

.Fasi
. Aggiungere il repository Trident Helm:
+
[source, console]
----
helm repo add netapp-trident https://artifacthub.io/packages/helm/netapp-trident/trident-operator
----
. Utilizzare `helm install` e specificare un nome per la distribuzione e la posizione del Registro di sistema dell'immagine. Lo link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Immagini Trident e CSI"] può trovarsi in un registro o in registri diversi, ma tutte le immagini CSI devono trovarsi nello stesso registro. Negli esempi, `100.2502.0` è la versione di Trident che si sta installando.
+
[role="tabbed-block"]
====
.Immagini in un registro
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2502.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
.Immagini in diversi registri
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2502.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:25.02.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:25.02 --set tridentImage=<your-registry>/trident:25.02.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
+

NOTE: Se è già stato creato uno spazio dei nomi per Trident, il `--create-namespace` parametro non creerà uno spazio dei nomi aggiuntivo.



È possibile utilizzare `helm list` per esaminare i dettagli dell'installazione come nome, spazio dei nomi, grafico, stato, versione dell'app, e numero di revisione.



== Passare i dati di configurazione durante l'installazione

Esistono due modi per passare i dati di configurazione durante l'installazione:

[cols="2"]
|===
| Opzione | Descrizione 


| `--values` (o `-f`)  a| 
Specificare un file YAML con override. Questo valore può essere specificato più volte e il file più a destra avrà la precedenza.



| `--set`  a| 
Specificare le sostituzioni sulla riga di comando.

|===
Ad esempio, per modificare il valore predefinito di `debug`, eseguire il comando seguente dove si trova `100.2502.0` la versione di Trident che si sta installando:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2502.0  --create-namespace --namespace trident --set tridentDebug=true
----
Per aggiungere il valore nodePrep, eseguire il comando seguente:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2502.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----


== Opzioni di configurazione

Questa tabella e il `values.yaml` file, che fa parte del grafico Helm, forniscono l'elenco delle chiavi e i loro valori predefiniti.


WARNING: Non rimuovere l'affinità predefinita dal file Values.yaml. Se si desidera fornire un'affinità personalizzata, estendere l'affinità predefinita.

[cols="3"]
|===
| Opzione | Descrizione | Predefinito 


| `nodeSelector` | Etichette dei nodi per l'assegnazione dei pod |  


| `podAnnotations` | Annotazioni Pod |  


| `deploymentAnnotations` | Annotazioni di implementazione |  


| `tolerations` | Pedaggi per l'assegnazione del pod |  


| `affinity` | Affinità per l'assegnazione del pod  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: Non rimuovere l'affinità predefinita dal file Values.yaml. Se si desidera fornire un'affinità personalizzata, estendere l'affinità predefinita.



| `tridentControllerPluginNodeSelector` | Selettori di nodi aggiuntivi per i pod. Per ulteriori informazioni, fare riferimento alla link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Comprensione dei pod controller e dei pod di nodi"] sezione. |  


| `tridentControllerPluginTolerations` | Ignora le tolleranze Kubernetes per i pod. Per ulteriori informazioni, fare riferimento alla link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Comprensione dei pod controller e dei pod di nodi"] sezione. |  


| `tridentNodePluginNodeSelector` | Selettori di nodi aggiuntivi per i pod. Per ulteriori informazioni, fare riferimento alla link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Comprensione dei pod controller e dei pod di nodi"] sezione. |  


| `tridentNodePluginTolerations` | Ignora le tolleranze Kubernetes per i pod. Per ulteriori informazioni, fare riferimento alla link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Comprensione dei pod controller e dei pod di nodi"] sezione. |  


| `imageRegistry` | Identifica il Registro di sistema per `trident-operator` , `trident` e altre immagini. Lasciare vuoto per accettare l'impostazione predefinita. IMPORTANTE: Quando si installa Trident in un repository privato, se si utilizza `imageRegistry` lo switch per specificare la posizione del repository, non utilizzare `/netapp/` nel percorso del repository. | "" 


| `imagePullPolicy` | Consente di impostare il criterio di pull dell'immagine per `trident-operator` . | `IfNotPresent` 


| `imagePullSecrets` | Consente di impostare i segreti di estrazione delle immagini per `trident-operator` , `trident` e altre immagini. |  


| `kubeletDir` | Consente di ignorare la posizione host dello stato interno del kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Consente di impostare il livello di registrazione dell'operatore Trident su: `trace`, `debug`, , `info`, `warn` `error` O `fatal`. | `"info"` 


| `operatorDebug` | Consente di impostare il livello di log dell'operatore Trident su debug. | `true` 


| `operatorImage` | Consente la sostituzione completa dell'immagine per `trident-operator`. | "" 


| `operatorImageTag` | Consente di sovrascrivere il tag dell' `trident-operator`immagine. | "" 


| `tridentIPv6` | Permette a Trident di lavorare in cluster IPv6. | `false` 


| `tridentK8sTimeout` | Esegue l'override del timeout predefinito di 30 secondi per la maggior parte delle operazioni API di Kubernetes (se diverso da zero, in secondi). | `0` 


| `tridentHttpRequestTimeout` | Ignora il timeout predefinito di 90 secondi per le richieste HTTP, con `0s` una durata infinita per il timeout. Non sono consentiti valori negativi. | `"90s"` 


| `tridentSilenceAutosupport` | Consente di disattivare la creazione di rapporti periodici AutoSupport Trident. | `false` 


| `tridentAutosupportImageTag` | Consente di sovrascrivere il tag dell'immagine per il contenitore Trident AutoSupport. | `<version>` 


| `tridentAutosupportProxy` | Consente al contenitore Trident AutoSupport di telefonare a casa tramite un proxy HTTP. | "" 


| `tridentLogFormat` | Consente di impostare il formato di registrazione Trident (`text`o `json`). | `"text"` 


| `tridentDisableAuditLog` | Disattiva il registro di controllo Trident. | `true` 


| `tridentLogLevel` | Consente di impostare il livello di registrazione di Trident su: `trace`, `debug`, `info`, , `warn` `error` O `fatal`. | `"info"` 


| `tridentDebug` | Consente di impostare il livello di registro di Trident su `debug`. | `false` 


| `tridentLogWorkflows` | Consente di attivare flussi di lavoro Trident specifici per la registrazione delle tracce o l'eliminazione dei registri. | "" 


| `tridentLogLayers` | Consente di attivare livelli Trident specifici per la registrazione delle tracce o la soppressione dei registri. | "" 


| `tridentImage` | Consente la sostituzione completa dell'immagine per Trident. | "" 


| `tridentImageTag` | Consente di sovrascrivere il tag dell'immagine per Trident. | "" 


| `tridentProbePort` | Consente di ignorare la porta predefinita utilizzata per le sonde liveness/readiness Kubernetes. | "" 


| `windows` | Consente di installare Trident sul nodo di lavoro Windows. | `false` 


| `enableForceDetach` | Consente di attivare la funzione di distacco forzato. | `false` 


| `excludePodSecurityPolicy` | Esclude la creazione della policy di sicurezza del pod operatore. | `false` 


| `nodePrep` | Permette a Trident di preparare i nodi del cluster Kubernetes per gestire i volumi utilizzando il protocollo storage specificato. *Attualmente, `iscsi` è l'unico valore supportato.* |  
|===