---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy-tridentctl.html 
keywords: deploy, Trident, methods, operator, tridentctl, helm, attributes, customize 
summary: È possibile utilizzare il programma di installazione di Trident per personalizzare la distribuzione. 
---
= Personalizzare l'installazione di tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il programma di installazione di Trident per personalizzare l'installazione.



== Informazioni sul programma di installazione

Il programma di installazione di Trident consente di personalizzare gli attributi. Ad esempio, se l'immagine Trident è stata copiata in un repository privato, è possibile specificare il nome dell'immagine utilizzando `--trident-image`. Se l'immagine Trident e le immagini sidecar CSI necessarie sono state copiate in un repository privato, potrebbe essere preferibile specificare la posizione di tale repository utilizzando `--image-registry` lo switch, che assume il formato `<registry FQDN>[:port]`.


IMPORTANT: Quando si installa Trident in un repository privato, se si utilizza `--image-registry` lo switch per specificare la posizione del repository, non utilizzare `/netapp/` nel percorso del repository. Ad esempio: `./tridentctl install --image-registry <image-registry> -n <namespace>`

Se stai utilizzando una distribuzione di Kubernetes, dove `kubelet` mantiene i suoi dati su un percorso diverso dal solito `/var/lib/kubelet`, puoi specificare il percorso alternativo utilizzando `--kubelet-dir`.

Se è necessario personalizzare l'installazione oltre a quanto consentito dall'argomento del programma di installazione, è possibile personalizzare i file di distribuzione. L'utilizzo del `--generate-custom-yaml` parametro crea i seguenti file YAML nella directory del programma di installazione `setup`:

* `trident-clusterrolebinding.yaml`
* `trident-deployment.yaml`
* `trident-crds.yaml`
* `trident-clusterrole.yaml`
* `trident-daemonset.yaml`
* `trident-service.yaml`
* `trident-namespace.yaml`
* `trident-serviceaccount.yaml`
* `trident-resourcequota.yaml`


Dopo aver generato questi file, è possibile modificarli in base alle proprie esigenze e utilizzarli `--use-custom-yaml` per installare la distribuzione personalizzata.

[source, console]
----
./tridentctl install -n trident --use-custom-yaml
----